- name: create ec2 instance and r53 records
  hosts: all
  connection: local
  vars:
    sg_id: sg-02e0791460060eb90
    ami_id: ami-0220d79f3f480ecf5
    env: dev
    instance:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      image_id: "{{ ami_id }}"  
      security_group: "{{ sg_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instance }}"
    register: ec2_output
  - name: print the output of ec2 instance
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"



